### ISSUE TITLE
Enabled block replacement [Enhancement]

### ISSUE THREAD

**Issue by KrazyMiner001** [jacobsjo/minecraft-jigsaw-preview#94]
I am working on a mod which has custom blocks and making structures using these blocks. The generator of course has no idea what these blocks are so it would be useful if there was a feature to replace any block it does not understand with a placeholder block

**Comment by jacobsjo** [comment]
The app could theoretically be made to load resource packs from mods to display those blocks properly. But a placeholder block seems like a good short-term fix :+1:
